### PR TITLE
Migrate to Jakarta EE 9

### PR DESCRIPTION
**Pull request by basil**

### CODE REVIEW

**Comment by basil** [comment]
@mbSmaga Can this please be released? This is needed to resolve [JENKINS-74846](https://issues.jenkins.io/browse/JENKINS-74846) on 2.479.1 LTS or newer.

**Comment by basil** [comment]
@judovana Can this please be merged and released? This is needed to fully support 2.479.1 LTS or newer.

**Comment by judovana** [comment]
Yup, no reason to block it seen. TYVM!

**Comment by judovana** [comment]
Despite  gh actions successful,  build fails:
```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk mvn clean install
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ org.jenkins-ci.plugins:nested-view:${revision}${changelist}, /home/jvanek/git/nested-view-plugin/pom.xml, line 18, column 14
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.jenkins-ci.plugins:nested-view:1.36-SNAPSHOT (/home/jvanek/git/nested-view-plugin/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ org.jenkins-ci.plugins:nested-view:${revision}${changelist}, /home/jvanek/git/nested-view-plugin/pom.xml, line 18, column 14
```

In case the `  <packaging>hpi</packaging>` is removed, it fails right afterwards.
```
[ERROR] Failed to execute goal on project nested-view: Could not resolve dependencies for project org.jenkins-ci.plugins:nested-view:jar:1.36-SNAPSHOT: The following artifacts could not be resolved: org.jenkins-ci.main:jenkins-war:executable-war:2.479.1 (absent): org.jenkins-ci.main:jenkins-war:executable-war:2.479.1 was not found in https://repo.jenkins-ci.org/public/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo.jenkins-ci.org has elapsed or updates are forced -> [Help 1]
```

The pom changes are always a bit of mystery for me, but the passed GH action made me less vigilant.

@basil  any thoughts?

**Comment by judovana** [comment]
That was ensured.
```
JAVA_HOME=/usr/lib/jvm/java-17-openjdk mvn  -version
Apache Maven 3.9.6 (Red Hat 3.9.6-6)
Maven home: /usr/share/maven
Java version: 17.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.fc40.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.11.5-200.fc40.x86_64", arch: "amd64", family: "unix"
```

**Comment by basil** [comment]
That configuration should be working fine.

**Comment by judovana** [comment]
Cleaning the .m2 did nto worked. Reverting the commit made it build-able again.  Hmm

**Comment by basil** [comment]
I think there must be something wrong with your local configuration, as this works for me:

```
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/maven
Java version: 17.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-125-generic", arch: "amd64", family: "unix"
```

**Comment by judovana** [comment]
I will try newer mvn.

**Comment by judovana** [comment]
and indeed
```
-----
 jvanek  jvanek  08:26:38  ~  git  nested-view-plugin  master  $  JAVA_HOME=/usr/lib/jvm/java-17-openjdk ~/Desktop/apache-maven-3.9.9/bin/mvn  -version
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /home/jvanek/Desktop/apache-maven-3.9.9
Java version: 17.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.fc40.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.11.5-200.fc40.x86_64", arch: "amd64", family: "unix"
```

Did it s job and its built. Interesting. Thanx!

**Comment by judovana** [comment]
Release out. hth. ty!

**Pull request merged**
